### ISSUE TITLE
QR code logger problem

### ISSUE THREAD

**Issue by cornflaek21** [verlox/Discord-QR-Token-Logger#2]
Hi 
i have a problem with the discord QR code logger.
it dont show the image of the QR code on the left
here a photo:
![unknown](https://user-images.githubusercontent.com/103385319/170835196-577627f2-b2e5-4abd-af19-752cfd23569b.png)

**Comment by verlox** [comment]
found issue, will post update when it is fixed

**Comment by verlox** [comment]
fixed in commit 8004b61f7c0c1e9f4ba6894981ae6ff9040571d9. [Download](https://github.com/verlox/Discord-QR-Token-Logger/releases/tag/v1.5.2)
