### ISSUE TITLE
'devenv' and 'nuget' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by CF-Trail** [verlox/Discord-QR-Token-Logger#3]
![image](https://user-images.githubusercontent.com/106690765/171995769-774c1b9f-0ef6-4eb2-ba43-fdabca662c59.png)

**Comment by verlox** [comment]
Use this download [here](https://github.com/verlox/Discord-QR-Token-Logger/releases/tag/v1.5.2). That is a file I added out of convenience for myself.
