### ISSUE TITLE
Actual help or a tutorial?

### ISSUE THREAD

**Issue by NotaKennen** [verlox/Discord-QR-Token-Logger#5]
I know you said in a different issue that you need to click on the .exe file, but can you do actual explaining on what everything does and how to do it? Is the .exe a setup, or is it the grabber? Do I need to config something from somewhere and how do I properly use it? Just some explaining of stuff please?

**Comment by Skemiil** [comment]
Maybe actually look through the code, use your brain and stop skidding.

**Comment by verlox** [comment]
run the file called `Discord-QR-Token-Stealer.exe`. click the template image after it fills in the qr code to copy it. have someone scan it. then itll login and fill all the fields.
